Mode: debug
ProgramName: ""
BaseURL: ""
Author: ""
Listen: "0.0.0.0"
Port: "8001"
OpenGauss:
    Host: "1.92.80.233"
    Port: "26000"
    User: "user1"
    Pass: "User1@passwd"
    Database: "databaselab"
